server:
  port: 8020

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/login
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
